kowainik/life-sync

- life-sync.cabal
- src/Life/Configuration.hs
- stack-8.4.3.yaml
- stack.yaml
> [#2] Switch toml-parser to tomland

- life-sync.cabal
- src/Life/Configuration.hs
- test/Spec.hs
- test/Test/Roundtrip.hs
> [#15] Add roundtrip property test for config

- life-sync.cabal
- src/Life/Github.hs
- src/Life/Main/Init.hs
- src/Life/Main/Update.hs
- src/Life/Message.hs
> [#8] Add colorful error handling

- app/Main.hs
- app/Options.hs
- life-sync.cabal
- src/Life/Github.hs
- src/Life/Main/Add.hs
- src/Life/Main/Remove.hs
Resolves #19 
P.S. I probably should have catch exceptions..
> [#5] Add life remove command

- life-sync.cabal
- src/Life/Configuration.hs
- src/Life/Main/Init.hs
- test/Test/Roundtrip.hs
Resolves #4
This is how it looks like. I'm not satisfied with the output (alignment is slightly mixed) but dunno what to do with it... Any suggestions?
> [#4] Add list of predefined files to 'life init'

- src/Life/Configuration.hs
- src/Life/Github.hs
- src/Life/Main/Add.hs
- src/Life/Main/Init.hs
- src/Life/Main/Remove.hs
- src/Life/Message.hs
- src/Life/Shell.hs
> [#21] Refactor check for .life and dotfiles

- app/Main.hs
- app/Options.hs
- src/Life/Configuration.hs
- src/Life/Github.hs
- src/Life/Main/Add.hs
- src/Life/Main/Remove.hs
> [#22] Add --dir --file options

- app/Main.hs
- app/Options.hs
- life-sync.cabal
- src/Life/Configuration.hs
- src/Life/Github.hs
- src/Life/Main/Add.hs
- src/Life/Main/Init.hs
- src/Life/Main/Push.hs
- src/Life/Validation.hs
> [#12] Add life push command

- src/Life/Github.hs
- src/Life/Main/Add.hs
- src/Life/Main/Push.hs
- src/Life/Main/Remove.hs
- src/Life/Shell.hs
> [#26] Check if repository is in sync with remote

- app/Main.hs
- app/Options.hs
- life-sync.cabal
- src/Life/Configuration.hs
- src/Life/Github.hs
- src/Life/Main/Add.hs
- src/Life/Main/Pull.hs
- src/Life/Main/Push.hs
- src/Life/Main/Remove.hs
- src/Life/Message.hs
Resolves #6 
It works. I've tested it on mac with the following command:
```shell
$ life pull ChShersh --no-file .bashrc --no-file .gitconfig --no-file .profile --no-file .spacemacs
```
Not sure about behaviour in all cases though... Maybe it should be different somewhere.
> [#6] Implement 'life pull' command

- src/Life/Github.hs
- src/Life/Main/Add.hs
- src/Life/Main/Init.hs
> [#32] Add git diff view before pushing

- src/Life/Configuration.hs
- src/Life/Github.hs
- src/Life/Shell.hs
> [#31] Show running commands

- README.md
Resolves #9
If you have any suggestions regarding English or structure of README, I appreciate them all!
> [#9] Write README

- CHANGELOG.md
- life-sync.cabal
- src/Life/Github.hs
- src/Life/Main/Add.hs
- src/Life/Main/Push.hs
- src/Life/Main/Remove.hs
> [#42] Branch newtype

- CHANGELOG.md
- life-sync.cabal
- src/Life/Main/Add.hs
> [#48] Fix minor bug with broken life add -d.

- CHANGELOG.md
- app/Options.hs
- life-sync.cabal
- src/Life/Configuration.hs
- src/Life/Core.hs
- src/Life/Github.hs
- src/Life/Main/Add.hs
- src/Life/Main/Init.hs
- src/Life/Main/Pull.hs
- src/Life/Main/Remove.hs
> [#49] core module

- .travis.yml
- CHANGELOG.md
- life-sync.cabal
- src/Life/Configuration.hs
- stack.yaml
> [#59] Bump to relude-0.4.0

- src/Life/Github.hs
> Implement doesBranchExist

- app/Options.hs
- src/Life/Github.hs
> Implement create new branch function

- app/Options.hs
- src/Life/Github.hs
- src/Life/Main/Init.hs
- src/Life/Main/Pull.hs
Resolves #36 
Signed-off-by: Sanchayan Maity <maitysanchayan@gmail.com>
> Get github username from gitconfig

- .github/CODEOWNERS
- .github/workflows/ci.yml
- .gitignore
- .travis.yml
- app/Main.hs
- app/Options.hs
- life-sync.cabal
- src/Life/Configuration.hs
- src/Life/Core.hs
- src/Life/Github.hs
- src/Life/Main/Add.hs
- src/Life/Validation.hs
- src/Prelude.hs
- stack.yaml
- test/Test/Roundtrip.hs
> [#65] Revive life-sync repo (cleanup, update, etc.)

- life-sync.cabal
- src/Life/Configuration.hs
- src/Life/Github.hs
- src/Life/Main/Add.hs
- src/Life/Main/Init.hs
- src/Life/Main/Pull.hs
- src/Life/Main/Push.hs
- src/Life/Main/Remove.hs
- src/Life/Path.hs
> [#70] Move to shellmet

- life-sync.cabal
- src/Life/Message.hs
> [#75] Move to colourista

- life-sync.cabal
- stack.yaml
- test/Spec.hs
- test/Test/Configuration.hs
> [#74] Get rid of tasty-* deps in tests

- .stylish-haskell.yaml
- life-sync.cabal
- src/Life/Configuration.hs
- src/Life/Main/Add.hs
- src/Life/Main/Push.hs
- src/Life/Main/Remove.hs
Add stylish-haskell file to the project
Refactor code a bit
Resolves #79
> [#79] Remove microlens-platform dep

- life-sync.cabal
- src/Life/Configuration.hs
- stack.yaml
- test/Test/Configuration.hs
> [#77] Optimize deps: remove 'fmt'

- app/Main.hs
- life-sync.cabal
- src/Life/Cli.hs
- src/Life/Main.hs
> [#69] Move CLI options inside library

- src/Life/Core.hs
- src/Life/Github.hs
- src/Life/Main/Push.hs
> [#51] Introduce `newtype CommitMsg` and use it

- CHANGELOG.md
- LICENSE
- life-sync.cabal
- src/Life/Cli.hs
- src/Life/Configuration.hs
- src/Life/Core.hs
- src/Life/Github.hs
- src/Life/Main.hs
- src/Life/Main/Add.hs
- src/Life/Main/Init.hs
- src/Life/Main/Pull.hs
- src/Life/Main/Push.hs
- src/Life/Main/Remove.hs
- src/Life/Message.hs
- src/Life/Path.hs
> [#84] Add meta info to library modules

- .travis.yml
> [#83] Add Travis binary releases

- README.md
> [#40] Add homebrew formula for mac

- README.md
> [#85] Add Ubuntu PPA
